### ISSUE TITLE
keepalive-interval and another problem

### ISSUE THREAD

**Issue by XEGARE** [zhsj/wghttp#4]
Hello.

``invalid argument for flag `/keepalive-interval' (expected time.Duration): time: missing unit in duration "20"``

On the current version I get an infinite connection. Lots of tries: `peer(jh1+…) - Sending handshake initiation`
On the version of July 18, everything connects perfectly

**Comment by zhsj** [comment]
> invalid argument for flag `/keepalive-interval' (expected time.Duration): time: missing unit in duration "20"

You should use `20s`. I may add the default unit `s` to the argument, to align other wireguard configuration.

**Comment by zhsj** [comment]
> On the current version I get an infinite connection. Lots of tries: peer(jh1+…) - Sending handshake initiation
On the version of July 18, everything connects perfectly

However commits from July 18 only affect the dns resolver, it shouldn't affect the wireguard connection...

**Comment by zhsj** [comment]
Okay, I checked my logs, and see some random `Sending handshake initiation`, but it doesn't see have any side effects?

**Comment by XEGARE** [comment]
> Okay, I checked my logs, and see some random , but it doesn't seem to have any side effects?`Sending handshake initiation`

It has. It doesn't connect.
![f](https://i.imgur.com/OTJO9OP.png)

**Comment by zhsj** [comment]
Could you check the log with prefix `Device config:`, and see if it's same with the version of July 18?

I have no clue that the changes since July 18 will affect the connection.

If the version of July 18 works, you can help me narrowing down the bug, by using `git bisect`. Or if you don't know how to use `git bisect`, you can just checkout each commit since July 18, and find the first commit that breaks the connection.

**Comment by XEGARE** [comment]
> July 18

![s](https://i.imgur.com/chV6uqf.png)

![s](https://i.imgur.com/qsOZ7vz.png)

**Comment by XEGARE** [comment]
> git bisect

4dc0f8e861bc174e49cf7fc3e562862e04fc09c0 is the first bad commit

**Comment by zhsj** [comment]
Thanks, I now know what happens.
